In [2]:
from matplotlib import pyplot as plt
import matplotlib.dates as md
import numpy as np
from osgeo import gdal
from datetime import datetime
import time
import os

# Operazioni di ETL sul dataset

In [4]:
path = r"./content/data"

dir_list =[x.split('.')[0] for x in os.listdir(path)]
dir_list.sort(key=lambda date: datetime.strptime(date, "%Y-%m-%d"))
print("Files and directories in '", path, "' :")
 
# prints all files
print(dir_list)
#
band1 = []
band2 = []
band3 = []
bandMatrix = []
for file in dir_list:
    tiff_file = r"content\data\\"+file+".tiff"
    dataset = gdal.Open(tiff_file)
    for i in range(0,12):
        try:
            if(len(bandMatrix[i].shape)==2):
                bandMatrix[i] = np.stack((bandMatrix[i],dataset.GetRasterBand(i+1).ReadAsArray()), axis=2)
            else:
                bandMatrix[i] = np.dstack((bandMatrix[i],dataset.GetRasterBand(i+1).ReadAsArray()))
        except IndexError:
            bandMatrix.append(dataset.GetRasterBand(i+1).ReadAsArray())

print(bandMatrix[0].shape)
print(bandMatrix[1].shape)
print(bandMatrix[2].shape)
#esempio: per estrarre il valore nel tempo del terreno nel 100,100 si ha:
print(bandMatrix[0][100,100,:])

Files and directories in ' ./content/data ' :
['2017-01-01', '2017-01-04', '2017-01-14', '2017-01-24', '2017-01-31', '2017-02-03', '2017-02-10', '2017-02-13', '2017-02-20', '2017-02-23', '2017-03-02', '2017-03-05', '2017-03-12', '2017-03-15', '2017-03-22', '2017-03-25', '2017-04-01', '2017-04-04', '2017-04-11', '2017-04-14', '2017-04-21', '2017-04-24', '2017-05-01', '2017-05-04', '2017-05-11', '2017-05-14', '2017-05-21', '2017-05-24', '2017-05-31', '2017-06-03', '2017-06-10', '2017-06-13', '2017-06-20', '2017-06-23', '2017-06-30', '2017-07-03', '2017-07-08', '2017-07-10', '2017-07-13', '2017-07-15', '2017-07-18', '2017-07-20', '2017-07-23', '2017-07-25', '2017-07-28', '2017-07-30', '2018-11-05', '2018-11-12', '2018-11-15', '2018-11-22', '2018-11-25', '2018-12-02', '2018-12-05', '2018-12-12', '2018-12-15', '2018-12-22', '2018-12-25']
(229, 302, 57)
(229, 302, 57)
(229, 302, 57)
[  547   996   377   301  4281 11781  9432 11878 11652  9192  1628  7461
  1172  1130  8149  1154  4267  1292 

# Calcolo degli indici NDVI e NDRE

In [22]:
NDVI = np.divide(np.subtract(bandMatrix[11],bandMatrix[7]),np.add(bandMatrix[11],bandMatrix[7]))
np.nan_to_num(NDVI,0)
print(NDVI)
NDRE = np.divide(np.subtract(bandMatrix[7],bandMatrix[4]),np.add(bandMatrix[7],bandMatrix[4]))
np.nan_to_num(NDRE,0)
print(NDRE)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[[0. 0. 0

C:\Users\pc\AppData\Local\Temp\ipykernel_16168\1500366461.py:1: RuntimeWarning: invalid value encountered in divide
  NDVI = np.divide(np.subtract(bandMatrix[11],bandMatrix[7]),np.add(bandMatrix[11],bandMatrix[7]))
C:\Users\pc\AppData\Local\Temp\ipykernel_16168\1500366461.py:4: RuntimeWarning: invalid value encountered in divide
  NDRE = np.divide(np.subtract(bandMatrix[7],bandMatrix[4]),np.add(bandMatrix[7],bandMatrix[4]))
