In [1]:
from matplotlib import pyplot as plt
import matplotlib.dates as md
import numpy as np
from osgeo import gdal
from datetime import datetime
import time
import os

# Operazioni di ETL sul dataset

In [2]:
path = r"./content/data"

dir_list =[x.split('.')[0] for x in os.listdir(path)]
dir_list.sort(key=lambda date: datetime.strptime(date, "%Y-%m-%d"))
print("Files and directories in '", path, "' :")
 
# prints all files
print(dir_list)
#
band1 = []
band2 = []
band3 = []
bandMatrix = []
for file in dir_list:
    tiff_file = r"content\data\\"+file+".tiff"
    dataset = gdal.Open(tiff_file)
    for i in range(0,12):
        try:
            if(len(bandMatrix[i].shape)==2):
                bandMatrix[i] = np.stack((bandMatrix[i],dataset.GetRasterBand(i+1).ReadAsArray()), axis=2)
            else:
                bandMatrix[i] = np.dstack((bandMatrix[i],dataset.GetRasterBand(i+1).ReadAsArray()))
        except IndexError:
            bandMatrix.append(dataset.GetRasterBand(i+1).ReadAsArray())

print(bandMatrix[0].shape)
print(bandMatrix[1].shape)
print(bandMatrix[2].shape)
#esempio: per estrarre il valore nel tempo del terreno nel 100,100 si ha:
print(bandMatrix[0][100,100,:])

Files and directories in ' ./content/data ' :
['2018-01-01', '2018-01-04', '2018-01-06', '2018-01-09', '2018-01-11', '2018-01-14', '2018-01-16', '2018-01-19', '2018-01-21', '2018-01-24', '2018-01-26', '2018-01-29', '2018-01-31', '2018-02-03', '2018-02-05', '2018-02-08', '2018-02-10', '2018-02-13', '2018-02-15', '2018-02-18', '2018-02-20', '2018-02-23', '2018-02-25', '2018-02-28', '2018-03-05', '2018-03-07', '2018-03-10', '2018-03-12', '2018-03-15', '2018-03-17', '2018-03-20', '2018-03-22', '2018-03-25', '2018-03-27', '2018-03-30', '2018-04-01', '2018-04-04', '2018-04-06', '2018-04-09', '2018-04-11', '2018-04-14', '2018-04-16', '2018-04-19', '2018-04-21', '2018-04-24', '2018-04-26', '2018-04-29', '2018-05-01', '2018-05-04', '2018-05-06', '2018-05-09', '2018-05-11', '2018-05-14', '2018-05-16', '2018-05-19', '2018-05-21', '2018-05-24', '2018-05-26', '2018-05-29', '2018-05-31', '2018-06-03', '2018-06-05', '2018-06-08', '2018-06-10', '2018-06-13', '2018-06-15', '2018-06-18', '2018-06-20', '

# Calcolo degli indici NDVI e NDRE

In [3]:
NDVI = np.divide(np.subtract(bandMatrix[11],bandMatrix[7]),np.add(bandMatrix[11],bandMatrix[7]))
np.nan_to_num(NDVI,0)
print(NDVI)
NDRE = np.divide(np.subtract(bandMatrix[7],bandMatrix[4]),np.add(bandMatrix[7],bandMatrix[4]))
np.nan_to_num(NDRE,0)
print(NDRE)

C:\Users\pc\AppData\Local\Temp\ipykernel_14092\1500366461.py:1: RuntimeWarning: invalid value encountered in divide
  NDVI = np.divide(np.subtract(bandMatrix[11],bandMatrix[7]),np.add(bandMatrix[11],bandMatrix[7]))
C:\Users\pc\AppData\Local\Temp\ipykernel_14092\1500366461.py:4: RuntimeWarning: invalid value encountered in divide
  NDRE = np.divide(np.subtract(bandMatrix[7],bandMatrix[4]),np.add(bandMatrix[7],bandMatrix[4]))


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[[0. 0. 0